server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/computermanageZGM
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.guotai.entity
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false